services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: sh -c "npx prisma db push --skip-generate && npx tsx prisma/seed.ts && node server.js"
        environment:
            NODE_ENV: production
            NEXT_PUBLIC_SITE_URL: 'https://timecapsule.alperates.com.tr'
            DATABASE_URL: 'postgresql://${POSTGRES_USER:-timecapsule}:${POSTGRES_PASSWORD:-change-me}@db:5432/${POSTGRES_DB:-timecapsule}?schema=public'
            COOLIFY_BRANCH: '"main"'
            COOLIFY_RESOURCE_UUID: qkjkf7bc79iyseqrrhyf3yn5
            COOLIFY_CONTAINER_NAME: web-qkjkf7bc79iyseqrrhyf3yn5-181643241662
            SERVICE_URL_WEB: 'https://timecapsule.alperates.com.tr'
            SERVICE_FQDN_WEB: timecapsule.alperates.com.tr
            COOLIFY_URL: 'https://timecapsule.alperates.com.tr'
            COOLIFY_FQDN: timecapsule.alperates.com.tr
            SERVICE_NAME_WEB: web
            SERVICE_NAME_DB: db
        depends_on:
            db:
                condition: service_healthy
        restart: always
        container_name: web-qkjkf7bc79iyseqrrhyf3yn5-181643241662
        labels:
            - coolify.managed=true
            - coolify.version=4.0.0
            - coolify.applicationId=10
            - coolify.type=application
            - coolify.name=web-qkjkf7bc79iyseqrrhyf3yn5-181643241662
            - coolify.resourceName=time-capsule
            - coolify.projectName=timecapsule
            - coolify.serviceName=time-capsule
            - coolify.environmentName=production
            - coolify.pullRequestId=0
            - traefik.enable=true
            - traefik.http.middlewares.gzip.compress=true
            - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
            - traefik.http.routers.http-0-qkjkf7bc79iyseqrrhyf3yn5-web.entryPoints=http
            - traefik.http.routers.http-0-qkjkf7bc79iyseqrrhyf3yn5-web.middlewares=redirect-to-https,crowdsec@file
            - 'traefik.http.routers.http-0-qkjkf7bc79iyseqrrhyf3yn5-web.rule=Host(`timecapsule.alperates.com.tr`)'
            - traefik.http.routers.https-0-qkjkf7bc79iyseqrrhyf3yn5-web.entryPoints=https
            - traefik.http.routers.https-0-qkjkf7bc79iyseqrrhyf3yn5-web.middlewares=gzip,crowdsec@file
            - 'traefik.http.routers.https-0-qkjkf7bc79iyseqrrhyf3yn5-web.rule=Host(`timecapsule.alperates.com.tr`)'
            - traefik.http.routers.https-0-qkjkf7bc79iyseqrrhyf3yn5-web.tls.certresolver=letsencrypt
            - traefik.http.routers.https-0-qkjkf7bc79iyseqrrhyf3yn5-web.tls=true
            - 'caddy_0.encode=zstd gzip'
            - 'caddy_0.handle_path.0_reverse_proxy={{upstreams}}'
            - 'caddy_0.handle_path=/*'
            - caddy_0.header=-Server
            - 'caddy_0.try_files={path} /index.html /index.php'
            - 'caddy_0=https://timecapsule.alperates.com.tr'
            - caddy_ingress_network=qkjkf7bc79iyseqrrhyf3yn5
        networks:
            qkjkf7bc79iyseqrrhyf3yn5: null
        env_file:
            - .env
        image: 'qkjkf7bc79iyseqrrhyf3yn5_web:97829b331390eb8ed4b4b3602f306e327d07ae57'
    db:
        image: 'postgres:15-alpine'
        environment:
            POSTGRES_USER: timecapsule
            POSTGRES_PASSWORD: e8SzNbApXiEXRjB5QzFqDAluqjAMwmnO
            POSTGRES_DB: timecapsule
            COOLIFY_BRANCH: '"main"'
            COOLIFY_RESOURCE_UUID: qkjkf7bc79iyseqrrhyf3yn5
            COOLIFY_CONTAINER_NAME: db-qkjkf7bc79iyseqrrhyf3yn5-181643244630
            SERVICE_URL_WEB: 'https://timecapsule.alperates.com.tr'
            SERVICE_FQDN_WEB: timecapsule.alperates.com.tr
            SERVICE_NAME_WEB: web
            SERVICE_NAME_DB: db
        volumes:
            - 'qkjkf7bc79iyseqrrhyf3yn5_postgres-data:/var/lib/postgresql/data'
        healthcheck:
            test:
                - CMD-SHELL
                - 'pg_isready -U ${POSTGRES_USER:-timecapsule}'
            interval: 5s
            timeout: 5s
            retries: 5
        restart: always
        container_name: db-qkjkf7bc79iyseqrrhyf3yn5-181643244630
        labels:
            - coolify.managed=true
            - coolify.version=4.0.0
            - coolify.applicationId=10
            - coolify.type=application
            - coolify.name=db-qkjkf7bc79iyseqrrhyf3yn5-181643244630
            - coolify.resourceName=time-capsule
            - coolify.projectName=timecapsule
            - coolify.serviceName=time-capsule
            - coolify.environmentName=production
            - coolify.pullRequestId=0
        networks:
            qkjkf7bc79iyseqrrhyf3yn5: null
        env_file:
            - .env
volumes:
    qkjkf7bc79iyseqrrhyf3yn5_postgres-data:
        name: qkjkf7bc79iyseqrrhyf3yn5_postgres-data
networks:
    qkjkf7bc79iyseqrrhyf3yn5:
        name: qkjkf7bc79iyseqrrhyf3yn5
        external: true
